name: Packer build and create machine image

on:
  pull_request:
    branches:
      - main

env:
  PACKER_LOG: "1"

jobs:
  build-machine-image:
    name: packer build and create machine image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packer
        uses: hashicorp/setup-packer@v2

      - name: Make all scripts executable
        run: chmod +x packer/*.sh

      - name: Initialize packer
        run: packer init ./packer

      - name: Configure AWS key and password
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_PASSWORD}}
          aws-region: ${{vars.aws_region}}

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_KEY}}

      - name: Install GCP SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build machine image
        run: |
          cd packer
          packer build \
            -var "aws_region=${{vars.AWS_REGION}}" \
            -var "aws_instance_type=${{vars.AWS_INSTANCE_TYPE}}" \
            -var "aws_source_ami=${{secrets.AWS_SOURCE_AMI}}" \
            -var "ssh_username=${{vars.SSH_USERNAME}}" \
            -var "aws_subnet_id=${{secrets.AWS_SUBNET_ID}}" \
            -var "aws_demo_account=${{secrets.AWS_DEMO_ACCOUNT}}" \
            -var "gcp_project_id=${{secrets.GCP_PROJECT_ID}}" \
            -var "gcp_zone=${{vars.GCP_ZONE}}" \
            -var "gcp_image_family=${{vars.GCP_IMAGE_FAMILY}}" \
            -var "gcp_image_project=${{vars.GCP_IMAGE_PROJECT}}" \
            -var "gcp_machine_type=${{vars.GCP_MACHINE_TYPE}}" \
            -var "DB_HOST=${{vars.DB_HOST}}" \
            -var "DB_USER=${{secrets.DB_USER}}" \
            -var "DB_PASSWORD=${{secrets.DB_PASSWORD}}" \
            -var "DB_NAME=${{vars.DB_NAME}}" \
            -var "PORT=${{vars.PORT}}" \
            -var "APP_GROUP=${{vars.APP_GROUP}}" \
            -var "APP_USER=${{vars.APP_USER}}" \
          .