name: Unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Install app and run unit tests
    runs-on: ubuntu-latest
    environment: test

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DB_PASSWORD}}
          MYSQL_DATABASE: ${{vars.DB_NAME}}
        ports:
          - ${{vars.PORT}}:${{vars.PORT}}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node modules
        run: npm install

      - name: Wait for MySQL server to start
        run: |
          while ! mysqladmin ping -h ${{vars.DB_HOST}} -u ${{secrets.DB_USER}} -p${{secrets.DB_PASSWORD}};
          do
            echo "Waiting for MySQL server start..."
            sleep 4
          done
          echo "MySQL server started"

      - name: Run test using environment variables
        env:
          DB_HOST: ${{vars.DB_HOST}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{vars.DB_NAME}}
          PORT: ${{ vars.DB_PORT }}
        run: npm test